### ISSUE TITLE
Missing r2 dependency

### ISSUE THREAD

**Issue by alacritythief** [reddit/reddit-plugin-place-opensource#2]
Upon running `sudo python setup.py develop`:

```
Processing dependencies for reddit-place==0.0
Searching for r2
Reading https://pypi.python.org/simple/r2/
Couldn't find index page for 'r2' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for r2
error: Could not find suitable distribution for Requirement.parse('r2')
```

Looking over https://pypi.python.org/simple/ there doesn't seem to be a r2 package to download.

**Comment by wbkboyer** [comment]
I'm not familiar with the code base, but I believe r2 is a package in the reddit repo: https://github.com/reddit/reddit/tree/master/r2

**Comment by alacritythief** [comment]
@wbkboyer Thank you for linking it to me, closing the issue.

**Comment by madbook** [comment]
.
